### ISSUE TITLE
When using Alien Weapon Cache to boost military, world-to-be-built displays "()"

### ISSUE THREAD

**Issue by ayao44** [bnordli/rftg#41] opened 2016-12-18 06:58 UTC
If you put yourself in a situation where Alien Weapon Cache is the only way to get required military to build a military world, the prompt will not display the amount of military strength needed.
E.g. Choose payment for Xeno-Occupied Rebel World ()

The parenthesis usually shows something like "3 military needed".  

See screenshot for example.
See game save file to jump to the same round it occurs (Choose double III, using NMT to build the first world, and you'll see the prompt message in question when you're directed to use powers to boost your 
military strength for the 2nd military world... either of the 8 or 9-defense Xeno military worlds)

[using Alien Weapons Cache for mili-str bug.zip](https://github.com/bnordli/rftg/files/659290/using.Alien.Weapons.Cache.for.mili-str.bug.zip)
![using alien weapons cache bug](https://cloud.githubusercontent.com/assets/16772854/21292061/34406f90-c4ac-11e6-8a32-a755131a9b2a.jpg)

**Comment by bnordli** [comment] 2016-12-18 07:52
Duplicate of #37.

**Closed by bnordli** 2016-12-18 07:52 UTC
