### ISSUE TITLE
"Couldn't Find Valid Payment"

### ISSUE THREAD

**Issue by dsnvwlmnt** [bnordli/rftg#48] opened 2017-06-14 06:54 UTC
6 player, Brink of War, Goals on, Takeovers on.

The previous round ended normally, action selection seemed fine. As soon as i click ok, the error below would popup and the game would crash. Reopening the program would resume the game at action selection. I tried a few actions ($, P-$, I+1) and the same problem always occurred. I do not have the seed #, unless there is a crash report/log generated somewhere that i don't know about.

![rftg bug](https://user-images.githubusercontent.com/14173022/27119072-35d5b572-5093-11e7-998b-709cf81a1040.png)

**Comment by bnordli** [comment] 2017-06-14 07:10
Most probably duplicate of #42

**Closed as completed by bnordli** 2017-06-14 07:10 UTC

**Comment by dsnvwlmnt** [comment] 2017-06-14 19:21
I'm confused. They don't seem related but i could be wrong. The bigger issue i'm confused about though, is both issues are closed. :P

**Comment by bnordli** [comment] 2017-06-14 19:23
The symptoms are exactly the same (BoW, error message.)

It's fixed in the code, but there hasn't been a new release yet.
