### ISSUE TITLE
Alien Booby Trap asking if I want to discard card to produce when all Windfall yellows are full

### ISSUE THREAD

**Issue by ayao44** [bnordli/rftg#45] opened 2017-01-19 07:48 UTC
It won't let me discard which is correct (which I would put this as an enhancement request), but it seems like it should just skip this entirely

[ABT asking to produce with no empty worlds.zip](https://github.com/bnordli/rftg/files/715944/ABT.asking.to.produce.with.no.empty.worlds.zip)

**Comment by dsnvwlmnt** [comment] 2017-01-19 08:08
This is likely a duplicate of #8.

**Comment by bnordli** [comment] 2017-01-19 08:44
Yes, this is a duplicate. The engine checks at the start of your produce phase whether there are any targets for Alien Booby Trap, but your Alien Rosetta Stone World produced on Alien Toy Shop, so there are no targets left, confusing the engine.

**Closed by bnordli** 2017-01-19 08:44 UTC
