### ISSUE TITLE
Couldn't Find Valid Payment popup error

### ISSUE THREAD

**Issue by ayao44** [bnordli/rftg#43] opened 2017-01-16 19:36 UTC
I got this when trying to pick Settle. The program gets forced closed.  When I open it up again, it resumes right before the point where that popup error occurs again.

Workaround was to undo a round, and pick Explore that previous round instead having done Settle.

[Valid Payment file and screenshot.zip](https://github.com/bnordli/rftg/files/709258/Valid.Payment.file.and.screenshot.zip)

**Comment by bnordli** [comment] 2017-01-16 20:58
Thanks for the report!

This is a duplicate of #42, and will be fixed in the next release.

**Closed by bnordli** 2017-01-16 20:58 UTC
